### ISSUE TITLE
No such file or directory at /usr/local/bin/ktImportText line 71

### ISSUE THREAD

**Issue by selin-kucukavsar** [marbl/Krona#59]
Hello, 
I am getting the error of 'No such file or directory at /usr/local/bin/ktImportText line 71'...
I am trying to use krona for my Qiime output. How can I solve the problem.

Thanks,
Selin

**Comment by coyk** [comment]
Had the exact same issue.  Tried using the sample data "GlobalPatterns" to see if I could get it to work.  Still didn't work, but gave different errors.  I suspect the error you mention is due to formatting of your dataset but I still haven't found a good resource as to what the correct taxonomic dataset should look like.

**Comment by ondovb** [comment]
Since KronaTools does not have an official Qiime importer or GlobalPatterns data set, these sound like issues beyond the scope of this forum.
