### ISSUE TITLE
Support accession to taxonomy mapping

### ISSUE THREAD

**Issue by chienchi** [marbl/Krona#9]
Dear developers,

Thanks for the great tool. We are using you beautiful and useful tool to display taxonomy classification result. Since NCBI is phasing out sequence GIs( use Accession.Version instead, https://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/ ),do you have any plan to support this transition? 

Regards,
Chienchi

**Comment by ondovb** [comment]
Hi Chienchi,
Thanks for the note, and yes, we should have a new version out to handle this before the change in September.

**Comment by mathiasbockwoldt** [comment]
I used your database for another project that is not published yet. With the GIs being removed, I thought about a solution for me that uses accession ids instead of gis. Each accession consists of up to 3 capital letters (or underscores) and a (up to) five-digit number. Approximately: `[A-Z_]{1,3}[0-9]{1,5}`.
A letter needs 5 bits, and 99999 (the highest possible number) 17 bits. 3*5+17 = 32 :smile:
I used a system where the first letter (if present) is multiplied with 2^27, the second letter with 2^22 and the third with 2^17. These numbers and the five-digit number are then OR-connected. The calculation back work similarly.
I don't know, how it works in combination with DNA accessions (that have a slightly different format), but maybe it is a good starting point for you if you want to keep the huge but fast database as you use it now. I have the Python code lying around for this approach. Just tell me, if you are interested.

**Comment by mathiasbockwoldt** [comment]
OK, forget about my previous comment. The accession ids don't follow the format given by NCBI. There are also other ids that may be used as accession ids, e.g. 3 letters plus 9 digits.
As my RAM is not big enough, I work on sorted and modified `prot.accession2taxid` files (given by NCBI) and a kind of binary search directly on the file. It's not O(1) as the old system, but still O(log N) (where N is the number of entries in the database). With some caching for often requested accession ids, this works fine for the first tests :smiley:
Maybe this may also be useful for you?!?

**Comment by ondovb** [comment]
Yes, I haven't really looked into this, so anything you're willing to share would be helpful (I may want to port to Perl for interoperability). It's too bad the bit packing doesn't quite work out.

**Comment by ondovb** [comment]
This is now implemented via binary search in [2.7](https://github.com/marbl/Krona/releases/tag/2.7).
